config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  # get 'logout/destroy'
  get 'logout', to: 'sessions#destroy'
  #get 'sessions/create'
  # get 'sessions/destory'
  resources :users
  resources :posts
 


  get 'admin' => 'admin#index'
  # get 'logout' => 'sessions#destroy'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    # delete 'logout' => :destroy
  end
  # get 'logout' => :destroy
  # delete 'logout' => :destroy
  root'admin#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorize
    protect_from_forgery with: :exception 
   protected
   def authorize
       unless User.find_by(id: session[:user_id])
           redirect_to login_url, alert: "لطفا اطلاعات کاربری را وارد کنید"
       end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize , :only => [:new, :create]
  def new
  end
  def destroy
    user = User.find_by(name: params[:name])
    session[:user_id] = nil
    redirect_to '/'   
  end
  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.name
      redirect_to user, alert: "کاربر وارد شد"
    else
      redirect_to login_url, alert: "نام کاربری یا گذر واژه صحیح نیست"
    end
  end
  # def destory
  #   User.find(session[:user_id]).destroy    
  #   session[:user_id] = nil         
  #   redirect_to '/' 
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: ' اطاعات کاربر با موفقیت ثبت شد' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'اطلاعات کاربر اصلاح شد' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'اطلاعات کاربر حذف شد' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<head>
<%= stylesheet_link_tag "clean-blog.css" %>
</head>
 <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/users/<%= session[:user_id] %>/edit"><%= session[:user_name] %> </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link" href="/posts">پست ها</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">پست جدید</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="users/new">ثبت نام</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="logout">خروج</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login">ورود</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">صفحه اصلی</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

      <header class="masthead bg1" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2>دانشگاه انفور ماتیک ایران</h2>
              <span class="subheading">وبلاگ و یاداشت های روزانه دانشجویان </span>
            </div>
          </div>
        </div>
      </div>
    </header>


<div class="container">

  <div class="row">
  <% @posts.each do |post| %>
    <div class="col-lg-12 col-md-12 mx-auto">
     
      <div class="post-preview ">
          <h2 class="post-title text-right">
           <%= post.name %>
          </h2>
         
          <h3 class="post-subtitle text-right">
            <%= post.body %>
          </h3>
       
        <p class="post-meta text-right"> تاریخ ارسال
        <%= post.created_at %>
         </p>
          <%= link_to '<button type="button" class="btn btn-success btn-sm">نمایش</button>'.html_safe, post %>
      </div>
       <hr>
    </div>
   
    <%end%>
  </div>
</div>



    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/developer_kev">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://t.me/hexytor">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-telegram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://gitlab.com/dev.kev">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted"> &copy;  پروژه وبلاگ m.ghorbani </p>
          </div>
        </div>
      </div>
    </footer>
   
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogUni</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
    <form class="form-horizontal" role="form" method="POST" action="/register">
        
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">عنوان</label>
            </div>
            <div class="col-md-6">
                  <div class="field input-group">
                  <div class="input-group-append">
                  <span class="input-group-text">عنوان</span>
                  </div>
                  <%= form.text_field :name, class:'form-control' %>
            </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">متن</label>
            </div>
            <div class="col-md-6">
                <div class="field input-group">
              <div class="input-group-append">
              <span class="input-group-text">متن</span>
              </div>
              <%= form.text_area :body, class:'form-control' %>
            </div>
            </div>
            <div class="col-md-3">
                
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <%= form.submit :ارسال , class:'btn btn-primary'%>
            </div>
        </div>
    </form>
    <% end %>

app/views/posts/edit.html.erb
<div class="alert alert-primary text-center"><h1> ویرایش پست</h1> </div>
<%= render 'form', post: @post %>

<%= link_to '<button type="button" class="btn btn-info btn-sm">نمایش</button>'.html_safe, @post %> |
<%= link_to '<button type="button" class="btn btn-danger btn-sm">بازگشت</button>'.html_safe, posts_path %>

app/views/posts/index.html.erb
<head>
<%= stylesheet_link_tag "clean-blog.css" %>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/users/<%= session[:user_id] %>/edit"><%= session[:user_name] %> </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link" href="/posts">پست ها</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">پست جدید</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="users/new">ثبت نام</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="logout">خروج</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login">ورود</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">صفحه اصلی</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<header class="masthead bg1" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2>دانشگاه انفور ماتیک ایران</h2>
              <span class="subheading">وبلاگ و یاداشت های روزانه دانشجویان </span>
            </div>
          </div>
        </div>
      </div>
</header>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">شناسه</th>
      <th scope="col">عنوان</th>
      <th scope="col">نمایش</th>
      <th scope="col">ویرایش</th>
      <th scope="col">حذف</th>
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <th><%= post.id %></th>
      <td><%= post.name %></td>
      <td><%= link_to '<button type="button" class="btn btn-success btn-sm">نمایش</button>'.html_safe, post %></td>
      <td><%= link_to '<button type="button" class="btn btn-info btn-sm">ویرایش</button>'.html_safe, edit_post_path(post.id) %></td>
      <td><%= link_to '<button type="button" class="btn btn-danger btn-sm">حذف</button>'.html_safe , post, method: :delete, data: { confirm: 'آیا از حذف مطلب اطمینان دارید؟' } %></td>
    </tr>
   <% end %>
  </tbody>
</table>

</body>
<%= link_to '<button type="button" class="btn btn-primary btn-lg btn-block">پست جدید</button>'.html_safe, new_post_path %>

app/views/posts/new.html.erb
<div class="alert alert-primary text-center"><h1> پست جدید</h1> </div>

<%= render 'form', post: @post %>

<%= link_to '<button type="button" class="btn btn-danger btn-sm">بازگشت</button>'.html_safe, posts_path %>

app/views/posts/show.html.erb
<head>
<%= stylesheet_link_tag "clean-blog.css" %>
</head>
<body>

    <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/users/<%= session[:user_id] %>/edit"><%= session[:user_name] %> </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link" href="/posts">پست ها</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">پست جدید</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="users/new">ثبت نام</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="logout">خروج</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login">ورود</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">صفحه اصلی</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    

      <header class="masthead bg2" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2>دانشگاه انفور ماتیک ایران</h2>
              <span class="subheading">وبلاگ و یاداشت های روزانه دانشجویان </span>
            </div>
          </div>
        </div>
      </div>
    </header>



<article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
              
            <h1 class="section-heading text-center"><%= @post.name %></h1>
            <hr>
            
            <p class="text-right"><%= @post.body %></p>

           
          </div>
          <%= link_to '<button type="button" class="btn btn-success btn-sm">ویرایش</button>'.html_safe, edit_post_path(@post) %>
          <%= link_to '<button type="button" class="btn btn-info btn-sm">بازگشت</button>'.html_safe, admin_path %>
         
          
        </div>
      </div>
    </article>
</body>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
    <form class="form-horizontal" role="form" method="POST" action="/register">
        
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">نام کاربری</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                        <%= form.text_field :name, class:'form-control' %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">گذر واژه</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                      <%= form.password_field :password, class:'form-control' %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">تکرار گذر واژه</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem">
                            <i class="fa fa-forward"></i>
                        </div>
                       <%= form.password_field :password_confirmation, class:'form-control' %>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <%= form.submit :ارسال , class:'btn btn-primary'%>
            </div>
        </div>
    </form>
    <% end %>

app/views/users/edit.html.erb
<div class="alert alert-primary text-center"><h1> ویرایش اطلاعات</h1> </div>

<%= render 'form', user: @user %>

<%= link_to '<button type="button" class="btn btn-info btn-sm">نمایش</button>'.html_safe, @user %> |
<%= link_to '<button type="button" class="btn btn-danger btn-sm">بازگشت</button>'.html_safe, user_path %>

app/views/users/index.html.erb
<head>
<%= stylesheet_link_tag "clean-blog.css" %>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/users/<%= session[:user_id] %>/edit"><%= session[:user_name] %> </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link" href="/posts">پست ها</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">پست جدید</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="users/new">ثبت نام</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="logout">خروج</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login">ورود</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">صفحه اصلی</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<header class="masthead bg1" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2>دانشگاه انفور ماتیک ایران</h2>
              <span class="subheading">وبلاگ و یاداشت های روزانه دانشجویان </span>
            </div>
          </div>
        </div>
      </div>
</header>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">شناسه</th>
      <th scope="col">نام کاربری</th>
      <th scope="col">نمایش</th>
      <th scope="col">ویرایش</th>
      <th scope="col">حذف</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th><%= user.id %></th>
      <td><%= user.name %></td>
      <td><%= link_to '<button type="button" class="btn btn-success btn-sm">نمایش</button>'.html_safe, user %></td>
      <td><%= link_to '<button type="button" class="btn btn-info btn-sm">ویرایش</button>'.html_safe, edit_user_path(user) %></td>
      <td><%= link_to '<button type="button" class="btn btn-danger btn-sm">حذف</button>'.html_safe , user, method: :delete, data: { confirm: 'آیا از حذف کاربر اطمینان دارید؟' } %></td>
    </tr>
   <% end %>
  </tbody>
</table>

</body>
<%= link_to '<button type="button" class="btn btn-primary btn-lg btn-block">کاربر جدید</button>'.html_safe, new_user_path %>

app/views/users/new.html.erb
<div class="alert alert-primary text-center"><h1> کاربر جدید</h1> </div>

<%= render 'form', user: @user %>

<%= link_to '<button type="button" class="btn btn-danger btn-sm">بازگشت</button>'.html_safe, users_path %>

app/views/users/show.html.erb
<div class="alert alert-primary text-center"><h1>  <%= @user.name %>:کاربر</h1> </div>



<%= link_to '<button type="button" class="btn btn-info btn-sm">ویرایش</button>'.html_safe, edit_user_path(@user) %> |
<%= link_to '<button type="button" class="btn btn-danger btn-sm">بازگشت</button>'.html_safe, users_path %>